/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-12-24 at 05:49:44 UTC 
 * Modify at your own risk.
 */

package com.inec.server.ws.gestionMantenimiento.model;

/**
 * Model definition for Ubigeo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gestionMantenimiento. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Ubigeo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String codeUbigeo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String departamento;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String distrito;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String idUbigeo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String operacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String provincia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long version;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCodeUbigeo() {
    return codeUbigeo;
  }

  /**
   * @param codeUbigeo codeUbigeo or {@code null} for none
   */
  public Ubigeo setCodeUbigeo(java.lang.String codeUbigeo) {
    this.codeUbigeo = codeUbigeo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDepartamento() {
    return departamento;
  }

  /**
   * @param departamento departamento or {@code null} for none
   */
  public Ubigeo setDepartamento(java.lang.String departamento) {
    this.departamento = departamento;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDistrito() {
    return distrito;
  }

  /**
   * @param distrito distrito or {@code null} for none
   */
  public Ubigeo setDistrito(java.lang.String distrito) {
    this.distrito = distrito;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdUbigeo() {
    return idUbigeo;
  }

  /**
   * @param idUbigeo idUbigeo or {@code null} for none
   */
  public Ubigeo setIdUbigeo(java.lang.String idUbigeo) {
    this.idUbigeo = idUbigeo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOperacion() {
    return operacion;
  }

  /**
   * @param operacion operacion or {@code null} for none
   */
  public Ubigeo setOperacion(java.lang.String operacion) {
    this.operacion = operacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProvincia() {
    return provincia;
  }

  /**
   * @param provincia provincia or {@code null} for none
   */
  public Ubigeo setProvincia(java.lang.String provincia) {
    this.provincia = provincia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVersion() {
    return version;
  }

  /**
   * @param version version or {@code null} for none
   */
  public Ubigeo setVersion(java.lang.Long version) {
    this.version = version;
    return this;
  }

  @Override
  public Ubigeo set(String fieldName, Object value) {
    return (Ubigeo) super.set(fieldName, value);
  }

  @Override
  public Ubigeo clone() {
    return (Ubigeo) super.clone();
  }

}
