/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-12-24 at 05:49:44 UTC 
 * Modify at your own risk.
 */

package com.inec.server.ws.gestionMantenimiento.model;

/**
 * Model definition for UsuarioFiscalizador.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gestionMantenimiento. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UsuarioFiscalizador extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String apellido;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String clave;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String codeUsuarioFiscalizador;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String codeZona;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String correoCorporativo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String correoPersonal;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String dniFiscalizador;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String estado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String idUsuarioFiscalizador;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombreZona;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String numero;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String operacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tokenFirebase;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long version;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getApellido() {
    return apellido;
  }

  /**
   * @param apellido apellido or {@code null} for none
   */
  public UsuarioFiscalizador setApellido(java.lang.String apellido) {
    this.apellido = apellido;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getClave() {
    return clave;
  }

  /**
   * @param clave clave or {@code null} for none
   */
  public UsuarioFiscalizador setClave(java.lang.String clave) {
    this.clave = clave;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCodeUsuarioFiscalizador() {
    return codeUsuarioFiscalizador;
  }

  /**
   * @param codeUsuarioFiscalizador codeUsuarioFiscalizador or {@code null} for none
   */
  public UsuarioFiscalizador setCodeUsuarioFiscalizador(java.lang.String codeUsuarioFiscalizador) {
    this.codeUsuarioFiscalizador = codeUsuarioFiscalizador;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCodeZona() {
    return codeZona;
  }

  /**
   * @param codeZona codeZona or {@code null} for none
   */
  public UsuarioFiscalizador setCodeZona(java.lang.String codeZona) {
    this.codeZona = codeZona;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCorreoCorporativo() {
    return correoCorporativo;
  }

  /**
   * @param correoCorporativo correoCorporativo or {@code null} for none
   */
  public UsuarioFiscalizador setCorreoCorporativo(java.lang.String correoCorporativo) {
    this.correoCorporativo = correoCorporativo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCorreoPersonal() {
    return correoPersonal;
  }

  /**
   * @param correoPersonal correoPersonal or {@code null} for none
   */
  public UsuarioFiscalizador setCorreoPersonal(java.lang.String correoPersonal) {
    this.correoPersonal = correoPersonal;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDniFiscalizador() {
    return dniFiscalizador;
  }

  /**
   * @param dniFiscalizador dniFiscalizador or {@code null} for none
   */
  public UsuarioFiscalizador setDniFiscalizador(java.lang.String dniFiscalizador) {
    this.dniFiscalizador = dniFiscalizador;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEstado() {
    return estado;
  }

  /**
   * @param estado estado or {@code null} for none
   */
  public UsuarioFiscalizador setEstado(java.lang.String estado) {
    this.estado = estado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdUsuarioFiscalizador() {
    return idUsuarioFiscalizador;
  }

  /**
   * @param idUsuarioFiscalizador idUsuarioFiscalizador or {@code null} for none
   */
  public UsuarioFiscalizador setIdUsuarioFiscalizador(java.lang.String idUsuarioFiscalizador) {
    this.idUsuarioFiscalizador = idUsuarioFiscalizador;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public UsuarioFiscalizador setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombreZona() {
    return nombreZona;
  }

  /**
   * @param nombreZona nombreZona or {@code null} for none
   */
  public UsuarioFiscalizador setNombreZona(java.lang.String nombreZona) {
    this.nombreZona = nombreZona;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNumero() {
    return numero;
  }

  /**
   * @param numero numero or {@code null} for none
   */
  public UsuarioFiscalizador setNumero(java.lang.String numero) {
    this.numero = numero;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOperacion() {
    return operacion;
  }

  /**
   * @param operacion operacion or {@code null} for none
   */
  public UsuarioFiscalizador setOperacion(java.lang.String operacion) {
    this.operacion = operacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTokenFirebase() {
    return tokenFirebase;
  }

  /**
   * @param tokenFirebase tokenFirebase or {@code null} for none
   */
  public UsuarioFiscalizador setTokenFirebase(java.lang.String tokenFirebase) {
    this.tokenFirebase = tokenFirebase;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVersion() {
    return version;
  }

  /**
   * @param version version or {@code null} for none
   */
  public UsuarioFiscalizador setVersion(java.lang.Long version) {
    this.version = version;
    return this;
  }

  @Override
  public UsuarioFiscalizador set(String fieldName, Object value) {
    return (UsuarioFiscalizador) super.set(fieldName, value);
  }

  @Override
  public UsuarioFiscalizador clone() {
    return (UsuarioFiscalizador) super.clone();
  }

}
