/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-12-24 at 05:49:47 UTC 
 * Modify at your own risk.
 */

package com.inec.server.ws.gestionIncidencia;

/**
 * Service definition for GestionIncidencia (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GestionIncidenciaRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class GestionIncidencia extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.22.0 of the gestionIncidencia library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://inec-145618.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "gestionIncidencia/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public GestionIncidencia(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  GestionIncidencia(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "actualizarIncidencia".
   *
   * This request holds the parameters needed by the gestionIncidencia server.  After setting any
   * optional parameters, call the {@link ActualizarIncidencia#execute()} method to invoke the remote
   * operation.
   *
   * @param aiCodeIncidencia
   * @param aiCodePartidoPolitico
   * @param aiCodeUsuario
   * @param aiDescripcion
   * @param aiDireccion
   * @param aiTipoIncidencia
   * @return the request
   */
  public ActualizarIncidencia actualizarIncidencia(java.lang.String aiCodeIncidencia, java.lang.String aiCodePartidoPolitico, java.lang.String aiCodeUsuario, java.lang.String aiDescripcion, java.lang.String aiDireccion, java.lang.String aiTipoIncidencia) throws java.io.IOException {
    ActualizarIncidencia result = new ActualizarIncidencia(aiCodeIncidencia, aiCodePartidoPolitico, aiCodeUsuario, aiDescripcion, aiDireccion, aiTipoIncidencia);
    initialize(result);
    return result;
  }

  public class ActualizarIncidencia extends GestionIncidenciaRequest<com.inec.server.ws.gestionIncidencia.model.ReturnValue> {

    private static final String REST_PATH = "actualizarIncidencia";

    /**
     * Create a request for the method "actualizarIncidencia".
     *
     * This request holds the parameters needed by the the gestionIncidencia server.  After setting
     * any optional parameters, call the {@link ActualizarIncidencia#execute()} method to invoke the
     * remote operation. <p> {@link ActualizarIncidencia#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param aiCodeIncidencia
     * @param aiCodePartidoPolitico
     * @param aiCodeUsuario
     * @param aiDescripcion
     * @param aiDireccion
     * @param aiTipoIncidencia
     * @since 1.13
     */
    protected ActualizarIncidencia(java.lang.String aiCodeIncidencia, java.lang.String aiCodePartidoPolitico, java.lang.String aiCodeUsuario, java.lang.String aiDescripcion, java.lang.String aiDireccion, java.lang.String aiTipoIncidencia) {
      super(GestionIncidencia.this, "POST", REST_PATH, null, com.inec.server.ws.gestionIncidencia.model.ReturnValue.class);
      this.aiCodeIncidencia = com.google.api.client.util.Preconditions.checkNotNull(aiCodeIncidencia, "Required parameter aiCodeIncidencia must be specified.");
      this.aiCodePartidoPolitico = com.google.api.client.util.Preconditions.checkNotNull(aiCodePartidoPolitico, "Required parameter aiCodePartidoPolitico must be specified.");
      this.aiCodeUsuario = com.google.api.client.util.Preconditions.checkNotNull(aiCodeUsuario, "Required parameter aiCodeUsuario must be specified.");
      this.aiDescripcion = com.google.api.client.util.Preconditions.checkNotNull(aiDescripcion, "Required parameter aiDescripcion must be specified.");
      this.aiDireccion = com.google.api.client.util.Preconditions.checkNotNull(aiDireccion, "Required parameter aiDireccion must be specified.");
      this.aiTipoIncidencia = com.google.api.client.util.Preconditions.checkNotNull(aiTipoIncidencia, "Required parameter aiTipoIncidencia must be specified.");
    }

    @Override
    public ActualizarIncidencia setAlt(java.lang.String alt) {
      return (ActualizarIncidencia) super.setAlt(alt);
    }

    @Override
    public ActualizarIncidencia setFields(java.lang.String fields) {
      return (ActualizarIncidencia) super.setFields(fields);
    }

    @Override
    public ActualizarIncidencia setKey(java.lang.String key) {
      return (ActualizarIncidencia) super.setKey(key);
    }

    @Override
    public ActualizarIncidencia setOauthToken(java.lang.String oauthToken) {
      return (ActualizarIncidencia) super.setOauthToken(oauthToken);
    }

    @Override
    public ActualizarIncidencia setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ActualizarIncidencia) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ActualizarIncidencia setQuotaUser(java.lang.String quotaUser) {
      return (ActualizarIncidencia) super.setQuotaUser(quotaUser);
    }

    @Override
    public ActualizarIncidencia setUserIp(java.lang.String userIp) {
      return (ActualizarIncidencia) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String aiCodeIncidencia;

    /**

     */
    public java.lang.String getAiCodeIncidencia() {
      return aiCodeIncidencia;
    }

    public ActualizarIncidencia setAiCodeIncidencia(java.lang.String aiCodeIncidencia) {
      this.aiCodeIncidencia = aiCodeIncidencia;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String aiCodePartidoPolitico;

    /**

     */
    public java.lang.String getAiCodePartidoPolitico() {
      return aiCodePartidoPolitico;
    }

    public ActualizarIncidencia setAiCodePartidoPolitico(java.lang.String aiCodePartidoPolitico) {
      this.aiCodePartidoPolitico = aiCodePartidoPolitico;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String aiCodeUsuario;

    /**

     */
    public java.lang.String getAiCodeUsuario() {
      return aiCodeUsuario;
    }

    public ActualizarIncidencia setAiCodeUsuario(java.lang.String aiCodeUsuario) {
      this.aiCodeUsuario = aiCodeUsuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String aiDescripcion;

    /**

     */
    public java.lang.String getAiDescripcion() {
      return aiDescripcion;
    }

    public ActualizarIncidencia setAiDescripcion(java.lang.String aiDescripcion) {
      this.aiDescripcion = aiDescripcion;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String aiDireccion;

    /**

     */
    public java.lang.String getAiDireccion() {
      return aiDireccion;
    }

    public ActualizarIncidencia setAiDireccion(java.lang.String aiDireccion) {
      this.aiDireccion = aiDireccion;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String aiTipoIncidencia;

    /**

     */
    public java.lang.String getAiTipoIncidencia() {
      return aiTipoIncidencia;
    }

    public ActualizarIncidencia setAiTipoIncidencia(java.lang.String aiTipoIncidencia) {
      this.aiTipoIncidencia = aiTipoIncidencia;
      return this;
    }

    @Override
    public ActualizarIncidencia set(String parameterName, Object value) {
      return (ActualizarIncidencia) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listarIncidencias".
   *
   * This request holds the parameters needed by the gestionIncidencia server.  After setting any
   * optional parameters, call the {@link ListarIncidencias#execute()} method to invoke the remote
   * operation.
   *
   * @param liDniUsuario
   * @return the request
   */
  public ListarIncidencias listarIncidencias(java.lang.String liDniUsuario) throws java.io.IOException {
    ListarIncidencias result = new ListarIncidencias(liDniUsuario);
    initialize(result);
    return result;
  }

  public class ListarIncidencias extends GestionIncidenciaRequest<com.inec.server.ws.gestionIncidencia.model.ReturnValue> {

    private static final String REST_PATH = "listarIncidencias";

    /**
     * Create a request for the method "listarIncidencias".
     *
     * This request holds the parameters needed by the the gestionIncidencia server.  After setting
     * any optional parameters, call the {@link ListarIncidencias#execute()} method to invoke the
     * remote operation. <p> {@link ListarIncidencias#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param liDniUsuario
     * @since 1.13
     */
    protected ListarIncidencias(java.lang.String liDniUsuario) {
      super(GestionIncidencia.this, "GET", REST_PATH, null, com.inec.server.ws.gestionIncidencia.model.ReturnValue.class);
      this.liDniUsuario = com.google.api.client.util.Preconditions.checkNotNull(liDniUsuario, "Required parameter liDniUsuario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListarIncidencias setAlt(java.lang.String alt) {
      return (ListarIncidencias) super.setAlt(alt);
    }

    @Override
    public ListarIncidencias setFields(java.lang.String fields) {
      return (ListarIncidencias) super.setFields(fields);
    }

    @Override
    public ListarIncidencias setKey(java.lang.String key) {
      return (ListarIncidencias) super.setKey(key);
    }

    @Override
    public ListarIncidencias setOauthToken(java.lang.String oauthToken) {
      return (ListarIncidencias) super.setOauthToken(oauthToken);
    }

    @Override
    public ListarIncidencias setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListarIncidencias) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListarIncidencias setQuotaUser(java.lang.String quotaUser) {
      return (ListarIncidencias) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListarIncidencias setUserIp(java.lang.String userIp) {
      return (ListarIncidencias) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String liDniUsuario;

    /**

     */
    public java.lang.String getLiDniUsuario() {
      return liDniUsuario;
    }

    public ListarIncidencias setLiDniUsuario(java.lang.String liDniUsuario) {
      this.liDniUsuario = liDniUsuario;
      return this;
    }

    @Override
    public ListarIncidencias set(String parameterName, Object value) {
      return (ListarIncidencias) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "registrarIncidenciaTransaction".
   *
   * This request holds the parameters needed by the gestionIncidencia server.  After setting any
   * optional parameters, call the {@link RegistrarIncidenciaTransaction#execute()} method to invoke
   * the remote operation.
   *
   * @param riCodePartidoPolitico
   * @param riDepartamento
   * @param riDescripcion
   * @param riDireccion
   * @param riDistrito
   * @param riDniUsuario
   * @param riFechaCelular
   * @param riLatitud
   * @param riLongitud
   * @param riProvincia
   * @param riTipoIncidencia
   * @param wListUrl
   * @param zListLatitud
   * @param zListLongitud
   * @return the request
   */
  public RegistrarIncidenciaTransaction registrarIncidenciaTransaction(java.lang.String riCodePartidoPolitico, java.lang.String riDepartamento, java.lang.String riDescripcion, java.lang.String riDireccion, java.lang.String riDistrito, java.lang.String riDniUsuario, java.lang.Long riFechaCelular, java.lang.Double riLatitud, java.lang.Double riLongitud, java.lang.String riProvincia, java.lang.String riTipoIncidencia, java.util.List<java.lang.String> wListUrl, java.util.List<java.lang.Double> zListLatitud, java.util.List<java.lang.Double> zListLongitud) throws java.io.IOException {
    RegistrarIncidenciaTransaction result = new RegistrarIncidenciaTransaction(riCodePartidoPolitico, riDepartamento, riDescripcion, riDireccion, riDistrito, riDniUsuario, riFechaCelular, riLatitud, riLongitud, riProvincia, riTipoIncidencia, wListUrl, zListLatitud, zListLongitud);
    initialize(result);
    return result;
  }

  public class RegistrarIncidenciaTransaction extends GestionIncidenciaRequest<com.inec.server.ws.gestionIncidencia.model.ReturnValue> {

    private static final String REST_PATH = "registrarIncidenciaTransaction";

    /**
     * Create a request for the method "registrarIncidenciaTransaction".
     *
     * This request holds the parameters needed by the the gestionIncidencia server.  After setting
     * any optional parameters, call the {@link RegistrarIncidenciaTransaction#execute()} method to
     * invoke the remote operation. <p> {@link RegistrarIncidenciaTransaction#initialize(com.google.ap
     * i.client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @param riCodePartidoPolitico
     * @param riDepartamento
     * @param riDescripcion
     * @param riDireccion
     * @param riDistrito
     * @param riDniUsuario
     * @param riFechaCelular
     * @param riLatitud
     * @param riLongitud
     * @param riProvincia
     * @param riTipoIncidencia
     * @param wListUrl
     * @param zListLatitud
     * @param zListLongitud
     * @since 1.13
     */
    protected RegistrarIncidenciaTransaction(java.lang.String riCodePartidoPolitico, java.lang.String riDepartamento, java.lang.String riDescripcion, java.lang.String riDireccion, java.lang.String riDistrito, java.lang.String riDniUsuario, java.lang.Long riFechaCelular, java.lang.Double riLatitud, java.lang.Double riLongitud, java.lang.String riProvincia, java.lang.String riTipoIncidencia, java.util.List<java.lang.String> wListUrl, java.util.List<java.lang.Double> zListLatitud, java.util.List<java.lang.Double> zListLongitud) {
      super(GestionIncidencia.this, "POST", REST_PATH, null, com.inec.server.ws.gestionIncidencia.model.ReturnValue.class);
      this.riCodePartidoPolitico = com.google.api.client.util.Preconditions.checkNotNull(riCodePartidoPolitico, "Required parameter riCodePartidoPolitico must be specified.");
      this.riDepartamento = com.google.api.client.util.Preconditions.checkNotNull(riDepartamento, "Required parameter riDepartamento must be specified.");
      this.riDescripcion = com.google.api.client.util.Preconditions.checkNotNull(riDescripcion, "Required parameter riDescripcion must be specified.");
      this.riDireccion = com.google.api.client.util.Preconditions.checkNotNull(riDireccion, "Required parameter riDireccion must be specified.");
      this.riDistrito = com.google.api.client.util.Preconditions.checkNotNull(riDistrito, "Required parameter riDistrito must be specified.");
      this.riDniUsuario = com.google.api.client.util.Preconditions.checkNotNull(riDniUsuario, "Required parameter riDniUsuario must be specified.");
      this.riFechaCelular = com.google.api.client.util.Preconditions.checkNotNull(riFechaCelular, "Required parameter riFechaCelular must be specified.");
      this.riLatitud = com.google.api.client.util.Preconditions.checkNotNull(riLatitud, "Required parameter riLatitud must be specified.");
      this.riLongitud = com.google.api.client.util.Preconditions.checkNotNull(riLongitud, "Required parameter riLongitud must be specified.");
      this.riProvincia = com.google.api.client.util.Preconditions.checkNotNull(riProvincia, "Required parameter riProvincia must be specified.");
      this.riTipoIncidencia = com.google.api.client.util.Preconditions.checkNotNull(riTipoIncidencia, "Required parameter riTipoIncidencia must be specified.");
      this.wListUrl = com.google.api.client.util.Preconditions.checkNotNull(wListUrl, "Required parameter wListUrl must be specified.");
      this.zListLatitud = com.google.api.client.util.Preconditions.checkNotNull(zListLatitud, "Required parameter zListLatitud must be specified.");
      this.zListLongitud = com.google.api.client.util.Preconditions.checkNotNull(zListLongitud, "Required parameter zListLongitud must be specified.");
    }

    @Override
    public RegistrarIncidenciaTransaction setAlt(java.lang.String alt) {
      return (RegistrarIncidenciaTransaction) super.setAlt(alt);
    }

    @Override
    public RegistrarIncidenciaTransaction setFields(java.lang.String fields) {
      return (RegistrarIncidenciaTransaction) super.setFields(fields);
    }

    @Override
    public RegistrarIncidenciaTransaction setKey(java.lang.String key) {
      return (RegistrarIncidenciaTransaction) super.setKey(key);
    }

    @Override
    public RegistrarIncidenciaTransaction setOauthToken(java.lang.String oauthToken) {
      return (RegistrarIncidenciaTransaction) super.setOauthToken(oauthToken);
    }

    @Override
    public RegistrarIncidenciaTransaction setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RegistrarIncidenciaTransaction) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RegistrarIncidenciaTransaction setQuotaUser(java.lang.String quotaUser) {
      return (RegistrarIncidenciaTransaction) super.setQuotaUser(quotaUser);
    }

    @Override
    public RegistrarIncidenciaTransaction setUserIp(java.lang.String userIp) {
      return (RegistrarIncidenciaTransaction) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String riCodePartidoPolitico;

    /**

     */
    public java.lang.String getRiCodePartidoPolitico() {
      return riCodePartidoPolitico;
    }

    public RegistrarIncidenciaTransaction setRiCodePartidoPolitico(java.lang.String riCodePartidoPolitico) {
      this.riCodePartidoPolitico = riCodePartidoPolitico;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String riDepartamento;

    /**

     */
    public java.lang.String getRiDepartamento() {
      return riDepartamento;
    }

    public RegistrarIncidenciaTransaction setRiDepartamento(java.lang.String riDepartamento) {
      this.riDepartamento = riDepartamento;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String riDescripcion;

    /**

     */
    public java.lang.String getRiDescripcion() {
      return riDescripcion;
    }

    public RegistrarIncidenciaTransaction setRiDescripcion(java.lang.String riDescripcion) {
      this.riDescripcion = riDescripcion;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String riDireccion;

    /**

     */
    public java.lang.String getRiDireccion() {
      return riDireccion;
    }

    public RegistrarIncidenciaTransaction setRiDireccion(java.lang.String riDireccion) {
      this.riDireccion = riDireccion;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String riDistrito;

    /**

     */
    public java.lang.String getRiDistrito() {
      return riDistrito;
    }

    public RegistrarIncidenciaTransaction setRiDistrito(java.lang.String riDistrito) {
      this.riDistrito = riDistrito;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String riDniUsuario;

    /**

     */
    public java.lang.String getRiDniUsuario() {
      return riDniUsuario;
    }

    public RegistrarIncidenciaTransaction setRiDniUsuario(java.lang.String riDniUsuario) {
      this.riDniUsuario = riDniUsuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long riFechaCelular;

    /**

     */
    public java.lang.Long getRiFechaCelular() {
      return riFechaCelular;
    }

    public RegistrarIncidenciaTransaction setRiFechaCelular(java.lang.Long riFechaCelular) {
      this.riFechaCelular = riFechaCelular;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double riLatitud;

    /**

     */
    public java.lang.Double getRiLatitud() {
      return riLatitud;
    }

    public RegistrarIncidenciaTransaction setRiLatitud(java.lang.Double riLatitud) {
      this.riLatitud = riLatitud;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double riLongitud;

    /**

     */
    public java.lang.Double getRiLongitud() {
      return riLongitud;
    }

    public RegistrarIncidenciaTransaction setRiLongitud(java.lang.Double riLongitud) {
      this.riLongitud = riLongitud;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String riProvincia;

    /**

     */
    public java.lang.String getRiProvincia() {
      return riProvincia;
    }

    public RegistrarIncidenciaTransaction setRiProvincia(java.lang.String riProvincia) {
      this.riProvincia = riProvincia;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String riTipoIncidencia;

    /**

     */
    public java.lang.String getRiTipoIncidencia() {
      return riTipoIncidencia;
    }

    public RegistrarIncidenciaTransaction setRiTipoIncidencia(java.lang.String riTipoIncidencia) {
      this.riTipoIncidencia = riTipoIncidencia;
      return this;
    }

    @com.google.api.client.util.Key
    private java.util.List<java.lang.String> wListUrl;

    /**

     */
    public java.util.List<java.lang.String> getWListUrl() {
      return wListUrl;
    }

    public RegistrarIncidenciaTransaction setWListUrl(java.util.List<java.lang.String> wListUrl) {
      this.wListUrl = wListUrl;
      return this;
    }

    @com.google.api.client.util.Key
    private java.util.List<java.lang.Double> zListLatitud;

    /**

     */
    public java.util.List<java.lang.Double> getZListLatitud() {
      return zListLatitud;
    }

    public RegistrarIncidenciaTransaction setZListLatitud(java.util.List<java.lang.Double> zListLatitud) {
      this.zListLatitud = zListLatitud;
      return this;
    }

    @com.google.api.client.util.Key
    private java.util.List<java.lang.Double> zListLongitud;

    /**

     */
    public java.util.List<java.lang.Double> getZListLongitud() {
      return zListLongitud;
    }

    public RegistrarIncidenciaTransaction setZListLongitud(java.util.List<java.lang.Double> zListLongitud) {
      this.zListLongitud = zListLongitud;
      return this;
    }

    @Override
    public RegistrarIncidenciaTransaction set(String parameterName, Object value) {
      return (RegistrarIncidenciaTransaction) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link GestionIncidencia}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link GestionIncidencia}. */
    @Override
    public GestionIncidencia build() {
      return new GestionIncidencia(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GestionIncidenciaRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGestionIncidenciaRequestInitializer(
        GestionIncidenciaRequestInitializer gestionincidenciaRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(gestionincidenciaRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
