/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-12-24 at 05:49:52 UTC 
 * Modify at your own risk.
 */

package com.inec.server.ws.gestionUsuario;

/**
 * Service definition for GestionUsuario (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GestionUsuarioRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class GestionUsuario extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.22.0 of the gestionUsuario library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://inec-145618.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "gestionUsuario/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public GestionUsuario(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  GestionUsuario(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "actualizarPassword".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link ActualizarPassword#execute()} method to invoke the remote
   * operation.
   *
   * @param apClaveUsuario
   * @param apConfirmarClave
   * @param apDniUsuario
   * @param apNuevaClave
   * @return the request
   */
  public ActualizarPassword actualizarPassword(java.lang.String apClaveUsuario, java.lang.String apConfirmarClave, java.lang.String apDniUsuario, java.lang.String apNuevaClave) throws java.io.IOException {
    ActualizarPassword result = new ActualizarPassword(apClaveUsuario, apConfirmarClave, apDniUsuario, apNuevaClave);
    initialize(result);
    return result;
  }

  public class ActualizarPassword extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "actualizarPassword";

    /**
     * Create a request for the method "actualizarPassword".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link ActualizarPassword#execute()} method to invoke the remote
     * operation. <p> {@link ActualizarPassword#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param apClaveUsuario
     * @param apConfirmarClave
     * @param apDniUsuario
     * @param apNuevaClave
     * @since 1.13
     */
    protected ActualizarPassword(java.lang.String apClaveUsuario, java.lang.String apConfirmarClave, java.lang.String apDniUsuario, java.lang.String apNuevaClave) {
      super(GestionUsuario.this, "POST", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.apClaveUsuario = com.google.api.client.util.Preconditions.checkNotNull(apClaveUsuario, "Required parameter apClaveUsuario must be specified.");
      this.apConfirmarClave = com.google.api.client.util.Preconditions.checkNotNull(apConfirmarClave, "Required parameter apConfirmarClave must be specified.");
      this.apDniUsuario = com.google.api.client.util.Preconditions.checkNotNull(apDniUsuario, "Required parameter apDniUsuario must be specified.");
      this.apNuevaClave = com.google.api.client.util.Preconditions.checkNotNull(apNuevaClave, "Required parameter apNuevaClave must be specified.");
    }

    @Override
    public ActualizarPassword setAlt(java.lang.String alt) {
      return (ActualizarPassword) super.setAlt(alt);
    }

    @Override
    public ActualizarPassword setFields(java.lang.String fields) {
      return (ActualizarPassword) super.setFields(fields);
    }

    @Override
    public ActualizarPassword setKey(java.lang.String key) {
      return (ActualizarPassword) super.setKey(key);
    }

    @Override
    public ActualizarPassword setOauthToken(java.lang.String oauthToken) {
      return (ActualizarPassword) super.setOauthToken(oauthToken);
    }

    @Override
    public ActualizarPassword setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ActualizarPassword) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ActualizarPassword setQuotaUser(java.lang.String quotaUser) {
      return (ActualizarPassword) super.setQuotaUser(quotaUser);
    }

    @Override
    public ActualizarPassword setUserIp(java.lang.String userIp) {
      return (ActualizarPassword) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String apClaveUsuario;

    /**

     */
    public java.lang.String getApClaveUsuario() {
      return apClaveUsuario;
    }

    public ActualizarPassword setApClaveUsuario(java.lang.String apClaveUsuario) {
      this.apClaveUsuario = apClaveUsuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String apConfirmarClave;

    /**

     */
    public java.lang.String getApConfirmarClave() {
      return apConfirmarClave;
    }

    public ActualizarPassword setApConfirmarClave(java.lang.String apConfirmarClave) {
      this.apConfirmarClave = apConfirmarClave;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String apDniUsuario;

    /**

     */
    public java.lang.String getApDniUsuario() {
      return apDniUsuario;
    }

    public ActualizarPassword setApDniUsuario(java.lang.String apDniUsuario) {
      this.apDniUsuario = apDniUsuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String apNuevaClave;

    /**

     */
    public java.lang.String getApNuevaClave() {
      return apNuevaClave;
    }

    public ActualizarPassword setApNuevaClave(java.lang.String apNuevaClave) {
      this.apNuevaClave = apNuevaClave;
      return this;
    }

    @Override
    public ActualizarPassword set(String parameterName, Object value) {
      return (ActualizarPassword) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "actualizarUsuario".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link ActualizarUsuario#execute()} method to invoke the remote
   * operation.
   *
   * @param auApellidos
   * @param auCodeZona
   * @param auCorreoInstitucional
   * @param auCorreoPersonal
   * @param auDni
   * @param auEstado
   * @param auNombres
   * @param auTelefono
   * @return the request
   */
  public ActualizarUsuario actualizarUsuario(java.lang.String auApellidos, java.lang.String auCodeZona, java.lang.String auCorreoInstitucional, java.lang.String auCorreoPersonal, java.lang.String auDni, java.lang.String auEstado, java.lang.String auNombres, java.lang.String auTelefono) throws java.io.IOException {
    ActualizarUsuario result = new ActualizarUsuario(auApellidos, auCodeZona, auCorreoInstitucional, auCorreoPersonal, auDni, auEstado, auNombres, auTelefono);
    initialize(result);
    return result;
  }

  public class ActualizarUsuario extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "actualizarUsuario";

    /**
     * Create a request for the method "actualizarUsuario".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link ActualizarUsuario#execute()} method to invoke the remote
     * operation. <p> {@link ActualizarUsuario#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param auApellidos
     * @param auCodeZona
     * @param auCorreoInstitucional
     * @param auCorreoPersonal
     * @param auDni
     * @param auEstado
     * @param auNombres
     * @param auTelefono
     * @since 1.13
     */
    protected ActualizarUsuario(java.lang.String auApellidos, java.lang.String auCodeZona, java.lang.String auCorreoInstitucional, java.lang.String auCorreoPersonal, java.lang.String auDni, java.lang.String auEstado, java.lang.String auNombres, java.lang.String auTelefono) {
      super(GestionUsuario.this, "POST", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.auApellidos = com.google.api.client.util.Preconditions.checkNotNull(auApellidos, "Required parameter auApellidos must be specified.");
      this.auCodeZona = com.google.api.client.util.Preconditions.checkNotNull(auCodeZona, "Required parameter auCodeZona must be specified.");
      this.auCorreoInstitucional = com.google.api.client.util.Preconditions.checkNotNull(auCorreoInstitucional, "Required parameter auCorreoInstitucional must be specified.");
      this.auCorreoPersonal = com.google.api.client.util.Preconditions.checkNotNull(auCorreoPersonal, "Required parameter auCorreoPersonal must be specified.");
      this.auDni = com.google.api.client.util.Preconditions.checkNotNull(auDni, "Required parameter auDni must be specified.");
      this.auEstado = com.google.api.client.util.Preconditions.checkNotNull(auEstado, "Required parameter auEstado must be specified.");
      this.auNombres = com.google.api.client.util.Preconditions.checkNotNull(auNombres, "Required parameter auNombres must be specified.");
      this.auTelefono = com.google.api.client.util.Preconditions.checkNotNull(auTelefono, "Required parameter auTelefono must be specified.");
    }

    @Override
    public ActualizarUsuario setAlt(java.lang.String alt) {
      return (ActualizarUsuario) super.setAlt(alt);
    }

    @Override
    public ActualizarUsuario setFields(java.lang.String fields) {
      return (ActualizarUsuario) super.setFields(fields);
    }

    @Override
    public ActualizarUsuario setKey(java.lang.String key) {
      return (ActualizarUsuario) super.setKey(key);
    }

    @Override
    public ActualizarUsuario setOauthToken(java.lang.String oauthToken) {
      return (ActualizarUsuario) super.setOauthToken(oauthToken);
    }

    @Override
    public ActualizarUsuario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ActualizarUsuario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ActualizarUsuario setQuotaUser(java.lang.String quotaUser) {
      return (ActualizarUsuario) super.setQuotaUser(quotaUser);
    }

    @Override
    public ActualizarUsuario setUserIp(java.lang.String userIp) {
      return (ActualizarUsuario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String auApellidos;

    /**

     */
    public java.lang.String getAuApellidos() {
      return auApellidos;
    }

    public ActualizarUsuario setAuApellidos(java.lang.String auApellidos) {
      this.auApellidos = auApellidos;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String auCodeZona;

    /**

     */
    public java.lang.String getAuCodeZona() {
      return auCodeZona;
    }

    public ActualizarUsuario setAuCodeZona(java.lang.String auCodeZona) {
      this.auCodeZona = auCodeZona;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String auCorreoInstitucional;

    /**

     */
    public java.lang.String getAuCorreoInstitucional() {
      return auCorreoInstitucional;
    }

    public ActualizarUsuario setAuCorreoInstitucional(java.lang.String auCorreoInstitucional) {
      this.auCorreoInstitucional = auCorreoInstitucional;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String auCorreoPersonal;

    /**

     */
    public java.lang.String getAuCorreoPersonal() {
      return auCorreoPersonal;
    }

    public ActualizarUsuario setAuCorreoPersonal(java.lang.String auCorreoPersonal) {
      this.auCorreoPersonal = auCorreoPersonal;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String auDni;

    /**

     */
    public java.lang.String getAuDni() {
      return auDni;
    }

    public ActualizarUsuario setAuDni(java.lang.String auDni) {
      this.auDni = auDni;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String auEstado;

    /**

     */
    public java.lang.String getAuEstado() {
      return auEstado;
    }

    public ActualizarUsuario setAuEstado(java.lang.String auEstado) {
      this.auEstado = auEstado;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String auNombres;

    /**

     */
    public java.lang.String getAuNombres() {
      return auNombres;
    }

    public ActualizarUsuario setAuNombres(java.lang.String auNombres) {
      this.auNombres = auNombres;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String auTelefono;

    /**

     */
    public java.lang.String getAuTelefono() {
      return auTelefono;
    }

    public ActualizarUsuario setAuTelefono(java.lang.String auTelefono) {
      this.auTelefono = auTelefono;
      return this;
    }

    @Override
    public ActualizarUsuario set(String parameterName, Object value) {
      return (ActualizarUsuario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "buscarUsuarioFiscalizadores".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link BuscarUsuarioFiscalizadores#execute()} method to invoke the
   * remote operation.
   *
   * @param bufPatron
   * @return the request
   */
  public BuscarUsuarioFiscalizadores buscarUsuarioFiscalizadores(java.lang.String bufPatron) throws java.io.IOException {
    BuscarUsuarioFiscalizadores result = new BuscarUsuarioFiscalizadores(bufPatron);
    initialize(result);
    return result;
  }

  public class BuscarUsuarioFiscalizadores extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "buscarUsuarioFiscalizadores";

    /**
     * Create a request for the method "buscarUsuarioFiscalizadores".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link BuscarUsuarioFiscalizadores#execute()} method to invoke
     * the remote operation. <p> {@link BuscarUsuarioFiscalizadores#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param bufPatron
     * @since 1.13
     */
    protected BuscarUsuarioFiscalizadores(java.lang.String bufPatron) {
      super(GestionUsuario.this, "POST", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.bufPatron = com.google.api.client.util.Preconditions.checkNotNull(bufPatron, "Required parameter bufPatron must be specified.");
    }

    @Override
    public BuscarUsuarioFiscalizadores setAlt(java.lang.String alt) {
      return (BuscarUsuarioFiscalizadores) super.setAlt(alt);
    }

    @Override
    public BuscarUsuarioFiscalizadores setFields(java.lang.String fields) {
      return (BuscarUsuarioFiscalizadores) super.setFields(fields);
    }

    @Override
    public BuscarUsuarioFiscalizadores setKey(java.lang.String key) {
      return (BuscarUsuarioFiscalizadores) super.setKey(key);
    }

    @Override
    public BuscarUsuarioFiscalizadores setOauthToken(java.lang.String oauthToken) {
      return (BuscarUsuarioFiscalizadores) super.setOauthToken(oauthToken);
    }

    @Override
    public BuscarUsuarioFiscalizadores setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (BuscarUsuarioFiscalizadores) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public BuscarUsuarioFiscalizadores setQuotaUser(java.lang.String quotaUser) {
      return (BuscarUsuarioFiscalizadores) super.setQuotaUser(quotaUser);
    }

    @Override
    public BuscarUsuarioFiscalizadores setUserIp(java.lang.String userIp) {
      return (BuscarUsuarioFiscalizadores) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String bufPatron;

    /**

     */
    public java.lang.String getBufPatron() {
      return bufPatron;
    }

    public BuscarUsuarioFiscalizadores setBufPatron(java.lang.String bufPatron) {
      this.bufPatron = bufPatron;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String bufCodeZona;

    /**

     */
    public java.lang.String getBufCodeZona() {
      return bufCodeZona;
    }

    public BuscarUsuarioFiscalizadores setBufCodeZona(java.lang.String bufCodeZona) {
      this.bufCodeZona = bufCodeZona;
      return this;
    }

    @Override
    public BuscarUsuarioFiscalizadores set(String parameterName, Object value) {
      return (BuscarUsuarioFiscalizadores) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "cerrarSesionFiscalizador".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link CerrarSesionFiscalizador#execute()} method to invoke the
   * remote operation.
   *
   * @param csfCodeSessionFiscalizador
   * @return the request
   */
  public CerrarSesionFiscalizador cerrarSesionFiscalizador(java.lang.String csfCodeSessionFiscalizador) throws java.io.IOException {
    CerrarSesionFiscalizador result = new CerrarSesionFiscalizador(csfCodeSessionFiscalizador);
    initialize(result);
    return result;
  }

  public class CerrarSesionFiscalizador extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "cerrarSesionFiscalizador";

    /**
     * Create a request for the method "cerrarSesionFiscalizador".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link CerrarSesionFiscalizador#execute()} method to invoke the
     * remote operation. <p> {@link CerrarSesionFiscalizador#initialize(com.google.api.client.googleap
     * is.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param csfCodeSessionFiscalizador
     * @since 1.13
     */
    protected CerrarSesionFiscalizador(java.lang.String csfCodeSessionFiscalizador) {
      super(GestionUsuario.this, "POST", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.csfCodeSessionFiscalizador = com.google.api.client.util.Preconditions.checkNotNull(csfCodeSessionFiscalizador, "Required parameter csfCodeSessionFiscalizador must be specified.");
    }

    @Override
    public CerrarSesionFiscalizador setAlt(java.lang.String alt) {
      return (CerrarSesionFiscalizador) super.setAlt(alt);
    }

    @Override
    public CerrarSesionFiscalizador setFields(java.lang.String fields) {
      return (CerrarSesionFiscalizador) super.setFields(fields);
    }

    @Override
    public CerrarSesionFiscalizador setKey(java.lang.String key) {
      return (CerrarSesionFiscalizador) super.setKey(key);
    }

    @Override
    public CerrarSesionFiscalizador setOauthToken(java.lang.String oauthToken) {
      return (CerrarSesionFiscalizador) super.setOauthToken(oauthToken);
    }

    @Override
    public CerrarSesionFiscalizador setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (CerrarSesionFiscalizador) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CerrarSesionFiscalizador setQuotaUser(java.lang.String quotaUser) {
      return (CerrarSesionFiscalizador) super.setQuotaUser(quotaUser);
    }

    @Override
    public CerrarSesionFiscalizador setUserIp(java.lang.String userIp) {
      return (CerrarSesionFiscalizador) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String csfCodeSessionFiscalizador;

    /**

     */
    public java.lang.String getCsfCodeSessionFiscalizador() {
      return csfCodeSessionFiscalizador;
    }

    public CerrarSesionFiscalizador setCsfCodeSessionFiscalizador(java.lang.String csfCodeSessionFiscalizador) {
      this.csfCodeSessionFiscalizador = csfCodeSessionFiscalizador;
      return this;
    }

    @Override
    public CerrarSesionFiscalizador set(String parameterName, Object value) {
      return (CerrarSesionFiscalizador) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "crearUsuario".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link CrearUsuario#execute()} method to invoke the remote
   * operation.
   *
   * @param cuApellidos
   * @param cuCodeZona
   * @param cuCorreoInstitucional
   * @param cuCorreoPersonal
   * @param cuDni
   * @param cuEstado
   * @param cuNombres
   * @param cuTelefono
   * @return the request
   */
  public CrearUsuario crearUsuario(java.lang.String cuApellidos, java.lang.String cuCodeZona, java.lang.String cuCorreoInstitucional, java.lang.String cuCorreoPersonal, java.lang.String cuDni, java.lang.String cuEstado, java.lang.String cuNombres, java.lang.String cuTelefono) throws java.io.IOException {
    CrearUsuario result = new CrearUsuario(cuApellidos, cuCodeZona, cuCorreoInstitucional, cuCorreoPersonal, cuDni, cuEstado, cuNombres, cuTelefono);
    initialize(result);
    return result;
  }

  public class CrearUsuario extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "crearUsuario";

    /**
     * Create a request for the method "crearUsuario".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link CrearUsuario#execute()} method to invoke the remote
     * operation. <p> {@link
     * CrearUsuario#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param cuApellidos
     * @param cuCodeZona
     * @param cuCorreoInstitucional
     * @param cuCorreoPersonal
     * @param cuDni
     * @param cuEstado
     * @param cuNombres
     * @param cuTelefono
     * @since 1.13
     */
    protected CrearUsuario(java.lang.String cuApellidos, java.lang.String cuCodeZona, java.lang.String cuCorreoInstitucional, java.lang.String cuCorreoPersonal, java.lang.String cuDni, java.lang.String cuEstado, java.lang.String cuNombres, java.lang.String cuTelefono) {
      super(GestionUsuario.this, "POST", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.cuApellidos = com.google.api.client.util.Preconditions.checkNotNull(cuApellidos, "Required parameter cuApellidos must be specified.");
      this.cuCodeZona = com.google.api.client.util.Preconditions.checkNotNull(cuCodeZona, "Required parameter cuCodeZona must be specified.");
      this.cuCorreoInstitucional = com.google.api.client.util.Preconditions.checkNotNull(cuCorreoInstitucional, "Required parameter cuCorreoInstitucional must be specified.");
      this.cuCorreoPersonal = com.google.api.client.util.Preconditions.checkNotNull(cuCorreoPersonal, "Required parameter cuCorreoPersonal must be specified.");
      this.cuDni = com.google.api.client.util.Preconditions.checkNotNull(cuDni, "Required parameter cuDni must be specified.");
      this.cuEstado = com.google.api.client.util.Preconditions.checkNotNull(cuEstado, "Required parameter cuEstado must be specified.");
      this.cuNombres = com.google.api.client.util.Preconditions.checkNotNull(cuNombres, "Required parameter cuNombres must be specified.");
      this.cuTelefono = com.google.api.client.util.Preconditions.checkNotNull(cuTelefono, "Required parameter cuTelefono must be specified.");
    }

    @Override
    public CrearUsuario setAlt(java.lang.String alt) {
      return (CrearUsuario) super.setAlt(alt);
    }

    @Override
    public CrearUsuario setFields(java.lang.String fields) {
      return (CrearUsuario) super.setFields(fields);
    }

    @Override
    public CrearUsuario setKey(java.lang.String key) {
      return (CrearUsuario) super.setKey(key);
    }

    @Override
    public CrearUsuario setOauthToken(java.lang.String oauthToken) {
      return (CrearUsuario) super.setOauthToken(oauthToken);
    }

    @Override
    public CrearUsuario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (CrearUsuario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CrearUsuario setQuotaUser(java.lang.String quotaUser) {
      return (CrearUsuario) super.setQuotaUser(quotaUser);
    }

    @Override
    public CrearUsuario setUserIp(java.lang.String userIp) {
      return (CrearUsuario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cuApellidos;

    /**

     */
    public java.lang.String getCuApellidos() {
      return cuApellidos;
    }

    public CrearUsuario setCuApellidos(java.lang.String cuApellidos) {
      this.cuApellidos = cuApellidos;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cuCodeZona;

    /**

     */
    public java.lang.String getCuCodeZona() {
      return cuCodeZona;
    }

    public CrearUsuario setCuCodeZona(java.lang.String cuCodeZona) {
      this.cuCodeZona = cuCodeZona;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cuCorreoInstitucional;

    /**

     */
    public java.lang.String getCuCorreoInstitucional() {
      return cuCorreoInstitucional;
    }

    public CrearUsuario setCuCorreoInstitucional(java.lang.String cuCorreoInstitucional) {
      this.cuCorreoInstitucional = cuCorreoInstitucional;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cuCorreoPersonal;

    /**

     */
    public java.lang.String getCuCorreoPersonal() {
      return cuCorreoPersonal;
    }

    public CrearUsuario setCuCorreoPersonal(java.lang.String cuCorreoPersonal) {
      this.cuCorreoPersonal = cuCorreoPersonal;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cuDni;

    /**

     */
    public java.lang.String getCuDni() {
      return cuDni;
    }

    public CrearUsuario setCuDni(java.lang.String cuDni) {
      this.cuDni = cuDni;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cuEstado;

    /**

     */
    public java.lang.String getCuEstado() {
      return cuEstado;
    }

    public CrearUsuario setCuEstado(java.lang.String cuEstado) {
      this.cuEstado = cuEstado;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cuNombres;

    /**

     */
    public java.lang.String getCuNombres() {
      return cuNombres;
    }

    public CrearUsuario setCuNombres(java.lang.String cuNombres) {
      this.cuNombres = cuNombres;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cuTelefono;

    /**

     */
    public java.lang.String getCuTelefono() {
      return cuTelefono;
    }

    public CrearUsuario setCuTelefono(java.lang.String cuTelefono) {
      this.cuTelefono = cuTelefono;
      return this;
    }

    @Override
    public CrearUsuario set(String parameterName, Object value) {
      return (CrearUsuario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "enviarCorreoFiscalizadores".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link EnviarCorreoFiscalizadores#execute()} method to invoke the
   * remote operation.
   *
   * @param ecfAsunto
   * @param ecfContenido
   * @param ecfCorreos
   * @return the request
   */
  public EnviarCorreoFiscalizadores enviarCorreoFiscalizadores(java.lang.String ecfAsunto, java.lang.String ecfContenido, java.lang.String ecfCorreos) throws java.io.IOException {
    EnviarCorreoFiscalizadores result = new EnviarCorreoFiscalizadores(ecfAsunto, ecfContenido, ecfCorreos);
    initialize(result);
    return result;
  }

  public class EnviarCorreoFiscalizadores extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "enviarCorreoFiscalizadores";

    /**
     * Create a request for the method "enviarCorreoFiscalizadores".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link EnviarCorreoFiscalizadores#execute()} method to invoke the
     * remote operation. <p> {@link EnviarCorreoFiscalizadores#initialize(com.google.api.client.google
     * apis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param ecfAsunto
     * @param ecfContenido
     * @param ecfCorreos
     * @since 1.13
     */
    protected EnviarCorreoFiscalizadores(java.lang.String ecfAsunto, java.lang.String ecfContenido, java.lang.String ecfCorreos) {
      super(GestionUsuario.this, "POST", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.ecfAsunto = com.google.api.client.util.Preconditions.checkNotNull(ecfAsunto, "Required parameter ecfAsunto must be specified.");
      this.ecfContenido = com.google.api.client.util.Preconditions.checkNotNull(ecfContenido, "Required parameter ecfContenido must be specified.");
      this.ecfCorreos = com.google.api.client.util.Preconditions.checkNotNull(ecfCorreos, "Required parameter ecfCorreos must be specified.");
    }

    @Override
    public EnviarCorreoFiscalizadores setAlt(java.lang.String alt) {
      return (EnviarCorreoFiscalizadores) super.setAlt(alt);
    }

    @Override
    public EnviarCorreoFiscalizadores setFields(java.lang.String fields) {
      return (EnviarCorreoFiscalizadores) super.setFields(fields);
    }

    @Override
    public EnviarCorreoFiscalizadores setKey(java.lang.String key) {
      return (EnviarCorreoFiscalizadores) super.setKey(key);
    }

    @Override
    public EnviarCorreoFiscalizadores setOauthToken(java.lang.String oauthToken) {
      return (EnviarCorreoFiscalizadores) super.setOauthToken(oauthToken);
    }

    @Override
    public EnviarCorreoFiscalizadores setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EnviarCorreoFiscalizadores) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EnviarCorreoFiscalizadores setQuotaUser(java.lang.String quotaUser) {
      return (EnviarCorreoFiscalizadores) super.setQuotaUser(quotaUser);
    }

    @Override
    public EnviarCorreoFiscalizadores setUserIp(java.lang.String userIp) {
      return (EnviarCorreoFiscalizadores) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String ecfAsunto;

    /**

     */
    public java.lang.String getEcfAsunto() {
      return ecfAsunto;
    }

    public EnviarCorreoFiscalizadores setEcfAsunto(java.lang.String ecfAsunto) {
      this.ecfAsunto = ecfAsunto;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String ecfContenido;

    /**

     */
    public java.lang.String getEcfContenido() {
      return ecfContenido;
    }

    public EnviarCorreoFiscalizadores setEcfContenido(java.lang.String ecfContenido) {
      this.ecfContenido = ecfContenido;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String ecfCorreos;

    /**

     */
    public java.lang.String getEcfCorreos() {
      return ecfCorreos;
    }

    public EnviarCorreoFiscalizadores setEcfCorreos(java.lang.String ecfCorreos) {
      this.ecfCorreos = ecfCorreos;
      return this;
    }

    @Override
    public EnviarCorreoFiscalizadores set(String parameterName, Object value) {
      return (EnviarCorreoFiscalizadores) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "estadoNotificacion".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link EstadoNotificacion#execute()} method to invoke the remote
   * operation.
   *
   * @param enCodeNotificacion
   * @return the request
   */
  public EstadoNotificacion estadoNotificacion(java.lang.String enCodeNotificacion) throws java.io.IOException {
    EstadoNotificacion result = new EstadoNotificacion(enCodeNotificacion);
    initialize(result);
    return result;
  }

  public class EstadoNotificacion extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "estadoNotificacion";

    /**
     * Create a request for the method "estadoNotificacion".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link EstadoNotificacion#execute()} method to invoke the remote
     * operation. <p> {@link EstadoNotificacion#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param enCodeNotificacion
     * @since 1.13
     */
    protected EstadoNotificacion(java.lang.String enCodeNotificacion) {
      super(GestionUsuario.this, "POST", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.enCodeNotificacion = com.google.api.client.util.Preconditions.checkNotNull(enCodeNotificacion, "Required parameter enCodeNotificacion must be specified.");
    }

    @Override
    public EstadoNotificacion setAlt(java.lang.String alt) {
      return (EstadoNotificacion) super.setAlt(alt);
    }

    @Override
    public EstadoNotificacion setFields(java.lang.String fields) {
      return (EstadoNotificacion) super.setFields(fields);
    }

    @Override
    public EstadoNotificacion setKey(java.lang.String key) {
      return (EstadoNotificacion) super.setKey(key);
    }

    @Override
    public EstadoNotificacion setOauthToken(java.lang.String oauthToken) {
      return (EstadoNotificacion) super.setOauthToken(oauthToken);
    }

    @Override
    public EstadoNotificacion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EstadoNotificacion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EstadoNotificacion setQuotaUser(java.lang.String quotaUser) {
      return (EstadoNotificacion) super.setQuotaUser(quotaUser);
    }

    @Override
    public EstadoNotificacion setUserIp(java.lang.String userIp) {
      return (EstadoNotificacion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String enCodeNotificacion;

    /**

     */
    public java.lang.String getEnCodeNotificacion() {
      return enCodeNotificacion;
    }

    public EstadoNotificacion setEnCodeNotificacion(java.lang.String enCodeNotificacion) {
      this.enCodeNotificacion = enCodeNotificacion;
      return this;
    }

    @Override
    public EstadoNotificacion set(String parameterName, Object value) {
      return (EstadoNotificacion) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "guardarPosicion".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link GuardarPosicion#execute()} method to invoke the remote
   * operation.
   *
   * @param gpCodeUsuario
   * @param gpDepartamento
   * @param gpDistrito
   * @param gpLatitud
   * @param gpLongitud
   * @param gpProvincia
   * @return the request
   */
  public GuardarPosicion guardarPosicion(java.lang.String gpCodeUsuario, java.lang.String gpDepartamento, java.lang.String gpDistrito, java.lang.Double gpLatitud, java.lang.Double gpLongitud, java.lang.String gpProvincia) throws java.io.IOException {
    GuardarPosicion result = new GuardarPosicion(gpCodeUsuario, gpDepartamento, gpDistrito, gpLatitud, gpLongitud, gpProvincia);
    initialize(result);
    return result;
  }

  public class GuardarPosicion extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "guardarPosicion";

    /**
     * Create a request for the method "guardarPosicion".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link GuardarPosicion#execute()} method to invoke the remote
     * operation. <p> {@link GuardarPosicion#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param gpCodeUsuario
     * @param gpDepartamento
     * @param gpDistrito
     * @param gpLatitud
     * @param gpLongitud
     * @param gpProvincia
     * @since 1.13
     */
    protected GuardarPosicion(java.lang.String gpCodeUsuario, java.lang.String gpDepartamento, java.lang.String gpDistrito, java.lang.Double gpLatitud, java.lang.Double gpLongitud, java.lang.String gpProvincia) {
      super(GestionUsuario.this, "POST", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.gpCodeUsuario = com.google.api.client.util.Preconditions.checkNotNull(gpCodeUsuario, "Required parameter gpCodeUsuario must be specified.");
      this.gpDepartamento = com.google.api.client.util.Preconditions.checkNotNull(gpDepartamento, "Required parameter gpDepartamento must be specified.");
      this.gpDistrito = com.google.api.client.util.Preconditions.checkNotNull(gpDistrito, "Required parameter gpDistrito must be specified.");
      this.gpLatitud = com.google.api.client.util.Preconditions.checkNotNull(gpLatitud, "Required parameter gpLatitud must be specified.");
      this.gpLongitud = com.google.api.client.util.Preconditions.checkNotNull(gpLongitud, "Required parameter gpLongitud must be specified.");
      this.gpProvincia = com.google.api.client.util.Preconditions.checkNotNull(gpProvincia, "Required parameter gpProvincia must be specified.");
    }

    @Override
    public GuardarPosicion setAlt(java.lang.String alt) {
      return (GuardarPosicion) super.setAlt(alt);
    }

    @Override
    public GuardarPosicion setFields(java.lang.String fields) {
      return (GuardarPosicion) super.setFields(fields);
    }

    @Override
    public GuardarPosicion setKey(java.lang.String key) {
      return (GuardarPosicion) super.setKey(key);
    }

    @Override
    public GuardarPosicion setOauthToken(java.lang.String oauthToken) {
      return (GuardarPosicion) super.setOauthToken(oauthToken);
    }

    @Override
    public GuardarPosicion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GuardarPosicion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GuardarPosicion setQuotaUser(java.lang.String quotaUser) {
      return (GuardarPosicion) super.setQuotaUser(quotaUser);
    }

    @Override
    public GuardarPosicion setUserIp(java.lang.String userIp) {
      return (GuardarPosicion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String gpCodeUsuario;

    /**

     */
    public java.lang.String getGpCodeUsuario() {
      return gpCodeUsuario;
    }

    public GuardarPosicion setGpCodeUsuario(java.lang.String gpCodeUsuario) {
      this.gpCodeUsuario = gpCodeUsuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String gpDepartamento;

    /**

     */
    public java.lang.String getGpDepartamento() {
      return gpDepartamento;
    }

    public GuardarPosicion setGpDepartamento(java.lang.String gpDepartamento) {
      this.gpDepartamento = gpDepartamento;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String gpDistrito;

    /**

     */
    public java.lang.String getGpDistrito() {
      return gpDistrito;
    }

    public GuardarPosicion setGpDistrito(java.lang.String gpDistrito) {
      this.gpDistrito = gpDistrito;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double gpLatitud;

    /**

     */
    public java.lang.Double getGpLatitud() {
      return gpLatitud;
    }

    public GuardarPosicion setGpLatitud(java.lang.Double gpLatitud) {
      this.gpLatitud = gpLatitud;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double gpLongitud;

    /**

     */
    public java.lang.Double getGpLongitud() {
      return gpLongitud;
    }

    public GuardarPosicion setGpLongitud(java.lang.Double gpLongitud) {
      this.gpLongitud = gpLongitud;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String gpProvincia;

    /**

     */
    public java.lang.String getGpProvincia() {
      return gpProvincia;
    }

    public GuardarPosicion setGpProvincia(java.lang.String gpProvincia) {
      this.gpProvincia = gpProvincia;
      return this;
    }

    @Override
    public GuardarPosicion set(String parameterName, Object value) {
      return (GuardarPosicion) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listarNotificaciones".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link ListarNotificaciones#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListarNotificaciones listarNotificaciones() throws java.io.IOException {
    ListarNotificaciones result = new ListarNotificaciones();
    initialize(result);
    return result;
  }

  public class ListarNotificaciones extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "listarNotificaciones";

    /**
     * Create a request for the method "listarNotificaciones".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link ListarNotificaciones#execute()} method to invoke the
     * remote operation. <p> {@link ListarNotificaciones#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListarNotificaciones() {
      super(GestionUsuario.this, "GET", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListarNotificaciones setAlt(java.lang.String alt) {
      return (ListarNotificaciones) super.setAlt(alt);
    }

    @Override
    public ListarNotificaciones setFields(java.lang.String fields) {
      return (ListarNotificaciones) super.setFields(fields);
    }

    @Override
    public ListarNotificaciones setKey(java.lang.String key) {
      return (ListarNotificaciones) super.setKey(key);
    }

    @Override
    public ListarNotificaciones setOauthToken(java.lang.String oauthToken) {
      return (ListarNotificaciones) super.setOauthToken(oauthToken);
    }

    @Override
    public ListarNotificaciones setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListarNotificaciones) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListarNotificaciones setQuotaUser(java.lang.String quotaUser) {
      return (ListarNotificaciones) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListarNotificaciones setUserIp(java.lang.String userIp) {
      return (ListarNotificaciones) super.setUserIp(userIp);
    }

    @Override
    public ListarNotificaciones set(String parameterName, Object value) {
      return (ListarNotificaciones) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listarPosicionFiscalizadors".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link ListarPosicionFiscalizadors#execute()} method to invoke the
   * remote operation.
   *
   * @param lpfDniUsuario
   * @return the request
   */
  public ListarPosicionFiscalizadors listarPosicionFiscalizadors(java.lang.String lpfDniUsuario) throws java.io.IOException {
    ListarPosicionFiscalizadors result = new ListarPosicionFiscalizadors(lpfDniUsuario);
    initialize(result);
    return result;
  }

  public class ListarPosicionFiscalizadors extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "listarPosicionFiscalizadors";

    /**
     * Create a request for the method "listarPosicionFiscalizadors".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link ListarPosicionFiscalizadors#execute()} method to invoke
     * the remote operation. <p> {@link ListarPosicionFiscalizadors#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param lpfDniUsuario
     * @since 1.13
     */
    protected ListarPosicionFiscalizadors(java.lang.String lpfDniUsuario) {
      super(GestionUsuario.this, "GET", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.lpfDniUsuario = com.google.api.client.util.Preconditions.checkNotNull(lpfDniUsuario, "Required parameter lpfDniUsuario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListarPosicionFiscalizadors setAlt(java.lang.String alt) {
      return (ListarPosicionFiscalizadors) super.setAlt(alt);
    }

    @Override
    public ListarPosicionFiscalizadors setFields(java.lang.String fields) {
      return (ListarPosicionFiscalizadors) super.setFields(fields);
    }

    @Override
    public ListarPosicionFiscalizadors setKey(java.lang.String key) {
      return (ListarPosicionFiscalizadors) super.setKey(key);
    }

    @Override
    public ListarPosicionFiscalizadors setOauthToken(java.lang.String oauthToken) {
      return (ListarPosicionFiscalizadors) super.setOauthToken(oauthToken);
    }

    @Override
    public ListarPosicionFiscalizadors setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListarPosicionFiscalizadors) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListarPosicionFiscalizadors setQuotaUser(java.lang.String quotaUser) {
      return (ListarPosicionFiscalizadors) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListarPosicionFiscalizadors setUserIp(java.lang.String userIp) {
      return (ListarPosicionFiscalizadors) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String lpfDniUsuario;

    /**

     */
    public java.lang.String getLpfDniUsuario() {
      return lpfDniUsuario;
    }

    public ListarPosicionFiscalizadors setLpfDniUsuario(java.lang.String lpfDniUsuario) {
      this.lpfDniUsuario = lpfDniUsuario;
      return this;
    }

    @Override
    public ListarPosicionFiscalizadors set(String parameterName, Object value) {
      return (ListarPosicionFiscalizadors) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listarRutas".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link ListarRutas#execute()} method to invoke the remote
   * operation.
   *
   * @param lpffDniUsuario
   * @param lpffFechaFormat
   * @return the request
   */
  public ListarRutas listarRutas(java.lang.String lpffDniUsuario, java.lang.String lpffFechaFormat) throws java.io.IOException {
    ListarRutas result = new ListarRutas(lpffDniUsuario, lpffFechaFormat);
    initialize(result);
    return result;
  }

  public class ListarRutas extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "listarRutas";

    /**
     * Create a request for the method "listarRutas".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link ListarRutas#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListarRutas#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param lpffDniUsuario
     * @param lpffFechaFormat
     * @since 1.13
     */
    protected ListarRutas(java.lang.String lpffDniUsuario, java.lang.String lpffFechaFormat) {
      super(GestionUsuario.this, "GET", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.lpffDniUsuario = com.google.api.client.util.Preconditions.checkNotNull(lpffDniUsuario, "Required parameter lpffDniUsuario must be specified.");
      this.lpffFechaFormat = com.google.api.client.util.Preconditions.checkNotNull(lpffFechaFormat, "Required parameter lpffFechaFormat must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListarRutas setAlt(java.lang.String alt) {
      return (ListarRutas) super.setAlt(alt);
    }

    @Override
    public ListarRutas setFields(java.lang.String fields) {
      return (ListarRutas) super.setFields(fields);
    }

    @Override
    public ListarRutas setKey(java.lang.String key) {
      return (ListarRutas) super.setKey(key);
    }

    @Override
    public ListarRutas setOauthToken(java.lang.String oauthToken) {
      return (ListarRutas) super.setOauthToken(oauthToken);
    }

    @Override
    public ListarRutas setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListarRutas) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListarRutas setQuotaUser(java.lang.String quotaUser) {
      return (ListarRutas) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListarRutas setUserIp(java.lang.String userIp) {
      return (ListarRutas) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String lpffDniUsuario;

    /**

     */
    public java.lang.String getLpffDniUsuario() {
      return lpffDniUsuario;
    }

    public ListarRutas setLpffDniUsuario(java.lang.String lpffDniUsuario) {
      this.lpffDniUsuario = lpffDniUsuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String lpffFechaFormat;

    /**

     */
    public java.lang.String getLpffFechaFormat() {
      return lpffFechaFormat;
    }

    public ListarRutas setLpffFechaFormat(java.lang.String lpffFechaFormat) {
      this.lpffFechaFormat = lpffFechaFormat;
      return this;
    }

    @Override
    public ListarRutas set(String parameterName, Object value) {
      return (ListarRutas) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listarRutasIntervalo".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link ListarRutasIntervalo#execute()} method to invoke the remote
   * operation.
   *
   * @param lriDniUsuario
   * @param lriFechaFin
   * @param lriFechaInicio
   * @return the request
   */
  public ListarRutasIntervalo listarRutasIntervalo(java.lang.String lriDniUsuario, java.lang.Long lriFechaFin, java.lang.Long lriFechaInicio) throws java.io.IOException {
    ListarRutasIntervalo result = new ListarRutasIntervalo(lriDniUsuario, lriFechaFin, lriFechaInicio);
    initialize(result);
    return result;
  }

  public class ListarRutasIntervalo extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "listarRutasIntervalo";

    /**
     * Create a request for the method "listarRutasIntervalo".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link ListarRutasIntervalo#execute()} method to invoke the
     * remote operation. <p> {@link ListarRutasIntervalo#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param lriDniUsuario
     * @param lriFechaFin
     * @param lriFechaInicio
     * @since 1.13
     */
    protected ListarRutasIntervalo(java.lang.String lriDniUsuario, java.lang.Long lriFechaFin, java.lang.Long lriFechaInicio) {
      super(GestionUsuario.this, "GET", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.lriDniUsuario = com.google.api.client.util.Preconditions.checkNotNull(lriDniUsuario, "Required parameter lriDniUsuario must be specified.");
      this.lriFechaFin = com.google.api.client.util.Preconditions.checkNotNull(lriFechaFin, "Required parameter lriFechaFin must be specified.");
      this.lriFechaInicio = com.google.api.client.util.Preconditions.checkNotNull(lriFechaInicio, "Required parameter lriFechaInicio must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListarRutasIntervalo setAlt(java.lang.String alt) {
      return (ListarRutasIntervalo) super.setAlt(alt);
    }

    @Override
    public ListarRutasIntervalo setFields(java.lang.String fields) {
      return (ListarRutasIntervalo) super.setFields(fields);
    }

    @Override
    public ListarRutasIntervalo setKey(java.lang.String key) {
      return (ListarRutasIntervalo) super.setKey(key);
    }

    @Override
    public ListarRutasIntervalo setOauthToken(java.lang.String oauthToken) {
      return (ListarRutasIntervalo) super.setOauthToken(oauthToken);
    }

    @Override
    public ListarRutasIntervalo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListarRutasIntervalo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListarRutasIntervalo setQuotaUser(java.lang.String quotaUser) {
      return (ListarRutasIntervalo) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListarRutasIntervalo setUserIp(java.lang.String userIp) {
      return (ListarRutasIntervalo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String lriDniUsuario;

    /**

     */
    public java.lang.String getLriDniUsuario() {
      return lriDniUsuario;
    }

    public ListarRutasIntervalo setLriDniUsuario(java.lang.String lriDniUsuario) {
      this.lriDniUsuario = lriDniUsuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long lriFechaFin;

    /**

     */
    public java.lang.Long getLriFechaFin() {
      return lriFechaFin;
    }

    public ListarRutasIntervalo setLriFechaFin(java.lang.Long lriFechaFin) {
      this.lriFechaFin = lriFechaFin;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long lriFechaInicio;

    /**

     */
    public java.lang.Long getLriFechaInicio() {
      return lriFechaInicio;
    }

    public ListarRutasIntervalo setLriFechaInicio(java.lang.Long lriFechaInicio) {
      this.lriFechaInicio = lriFechaInicio;
      return this;
    }

    @Override
    public ListarRutasIntervalo set(String parameterName, Object value) {
      return (ListarRutasIntervalo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listarUsuarios".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link ListarUsuarios#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListarUsuarios listarUsuarios() throws java.io.IOException {
    ListarUsuarios result = new ListarUsuarios();
    initialize(result);
    return result;
  }

  public class ListarUsuarios extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "listarUsuarios";

    /**
     * Create a request for the method "listarUsuarios".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link ListarUsuarios#execute()} method to invoke the remote
     * operation. <p> {@link ListarUsuarios#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListarUsuarios() {
      super(GestionUsuario.this, "GET", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListarUsuarios setAlt(java.lang.String alt) {
      return (ListarUsuarios) super.setAlt(alt);
    }

    @Override
    public ListarUsuarios setFields(java.lang.String fields) {
      return (ListarUsuarios) super.setFields(fields);
    }

    @Override
    public ListarUsuarios setKey(java.lang.String key) {
      return (ListarUsuarios) super.setKey(key);
    }

    @Override
    public ListarUsuarios setOauthToken(java.lang.String oauthToken) {
      return (ListarUsuarios) super.setOauthToken(oauthToken);
    }

    @Override
    public ListarUsuarios setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListarUsuarios) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListarUsuarios setQuotaUser(java.lang.String quotaUser) {
      return (ListarUsuarios) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListarUsuarios setUserIp(java.lang.String userIp) {
      return (ListarUsuarios) super.setUserIp(userIp);
    }

    @Override
    public ListarUsuarios set(String parameterName, Object value) {
      return (ListarUsuarios) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "loginUsuario".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link LoginUsuario#execute()} method to invoke the remote
   * operation.
   *
   * @param luClaveUsuario
   * @param luCorreoUsuario
   * @param luTokenFirebase
   * @return the request
   */
  public LoginUsuario loginUsuario(java.lang.String luClaveUsuario, java.lang.String luCorreoUsuario, java.lang.String luTokenFirebase) throws java.io.IOException {
    LoginUsuario result = new LoginUsuario(luClaveUsuario, luCorreoUsuario, luTokenFirebase);
    initialize(result);
    return result;
  }

  public class LoginUsuario extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "loginUsuario";

    /**
     * Create a request for the method "loginUsuario".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link LoginUsuario#execute()} method to invoke the remote
     * operation. <p> {@link
     * LoginUsuario#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param luClaveUsuario
     * @param luCorreoUsuario
     * @param luTokenFirebase
     * @since 1.13
     */
    protected LoginUsuario(java.lang.String luClaveUsuario, java.lang.String luCorreoUsuario, java.lang.String luTokenFirebase) {
      super(GestionUsuario.this, "POST", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.luClaveUsuario = com.google.api.client.util.Preconditions.checkNotNull(luClaveUsuario, "Required parameter luClaveUsuario must be specified.");
      this.luCorreoUsuario = com.google.api.client.util.Preconditions.checkNotNull(luCorreoUsuario, "Required parameter luCorreoUsuario must be specified.");
      this.luTokenFirebase = com.google.api.client.util.Preconditions.checkNotNull(luTokenFirebase, "Required parameter luTokenFirebase must be specified.");
    }

    @Override
    public LoginUsuario setAlt(java.lang.String alt) {
      return (LoginUsuario) super.setAlt(alt);
    }

    @Override
    public LoginUsuario setFields(java.lang.String fields) {
      return (LoginUsuario) super.setFields(fields);
    }

    @Override
    public LoginUsuario setKey(java.lang.String key) {
      return (LoginUsuario) super.setKey(key);
    }

    @Override
    public LoginUsuario setOauthToken(java.lang.String oauthToken) {
      return (LoginUsuario) super.setOauthToken(oauthToken);
    }

    @Override
    public LoginUsuario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (LoginUsuario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public LoginUsuario setQuotaUser(java.lang.String quotaUser) {
      return (LoginUsuario) super.setQuotaUser(quotaUser);
    }

    @Override
    public LoginUsuario setUserIp(java.lang.String userIp) {
      return (LoginUsuario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String luClaveUsuario;

    /**

     */
    public java.lang.String getLuClaveUsuario() {
      return luClaveUsuario;
    }

    public LoginUsuario setLuClaveUsuario(java.lang.String luClaveUsuario) {
      this.luClaveUsuario = luClaveUsuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String luCorreoUsuario;

    /**

     */
    public java.lang.String getLuCorreoUsuario() {
      return luCorreoUsuario;
    }

    public LoginUsuario setLuCorreoUsuario(java.lang.String luCorreoUsuario) {
      this.luCorreoUsuario = luCorreoUsuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String luTokenFirebase;

    /**

     */
    public java.lang.String getLuTokenFirebase() {
      return luTokenFirebase;
    }

    public LoginUsuario setLuTokenFirebase(java.lang.String luTokenFirebase) {
      this.luTokenFirebase = luTokenFirebase;
      return this;
    }

    @Override
    public LoginUsuario set(String parameterName, Object value) {
      return (LoginUsuario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "planificarNotificacion".
   *
   * This request holds the parameters needed by the gestionUsuario server.  After setting any
   * optional parameters, call the {@link PlanificarNotificacion#execute()} method to invoke the
   * remote operation.
   *
   * @param pnDiaFin
   * @param pnDiaInicio
   * @param pnFrecuencia
   * @param pnHoraFin
   * @param pnHoraInicio
   * @param pnTipoFrecuencia
   * @return the request
   */
  public PlanificarNotificacion planificarNotificacion(java.lang.String pnDiaFin, java.lang.String pnDiaInicio, java.lang.Integer pnFrecuencia, java.lang.Integer pnHoraFin, java.lang.Integer pnHoraInicio, java.lang.String pnTipoFrecuencia) throws java.io.IOException {
    PlanificarNotificacion result = new PlanificarNotificacion(pnDiaFin, pnDiaInicio, pnFrecuencia, pnHoraFin, pnHoraInicio, pnTipoFrecuencia);
    initialize(result);
    return result;
  }

  public class PlanificarNotificacion extends GestionUsuarioRequest<com.inec.server.ws.gestionUsuario.model.ReturnValue> {

    private static final String REST_PATH = "planificarNotificacion";

    /**
     * Create a request for the method "planificarNotificacion".
     *
     * This request holds the parameters needed by the the gestionUsuario server.  After setting any
     * optional parameters, call the {@link PlanificarNotificacion#execute()} method to invoke the
     * remote operation. <p> {@link PlanificarNotificacion#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param pnDiaFin
     * @param pnDiaInicio
     * @param pnFrecuencia
     * @param pnHoraFin
     * @param pnHoraInicio
     * @param pnTipoFrecuencia
     * @since 1.13
     */
    protected PlanificarNotificacion(java.lang.String pnDiaFin, java.lang.String pnDiaInicio, java.lang.Integer pnFrecuencia, java.lang.Integer pnHoraFin, java.lang.Integer pnHoraInicio, java.lang.String pnTipoFrecuencia) {
      super(GestionUsuario.this, "POST", REST_PATH, null, com.inec.server.ws.gestionUsuario.model.ReturnValue.class);
      this.pnDiaFin = com.google.api.client.util.Preconditions.checkNotNull(pnDiaFin, "Required parameter pnDiaFin must be specified.");
      this.pnDiaInicio = com.google.api.client.util.Preconditions.checkNotNull(pnDiaInicio, "Required parameter pnDiaInicio must be specified.");
      this.pnFrecuencia = com.google.api.client.util.Preconditions.checkNotNull(pnFrecuencia, "Required parameter pnFrecuencia must be specified.");
      this.pnHoraFin = com.google.api.client.util.Preconditions.checkNotNull(pnHoraFin, "Required parameter pnHoraFin must be specified.");
      this.pnHoraInicio = com.google.api.client.util.Preconditions.checkNotNull(pnHoraInicio, "Required parameter pnHoraInicio must be specified.");
      this.pnTipoFrecuencia = com.google.api.client.util.Preconditions.checkNotNull(pnTipoFrecuencia, "Required parameter pnTipoFrecuencia must be specified.");
    }

    @Override
    public PlanificarNotificacion setAlt(java.lang.String alt) {
      return (PlanificarNotificacion) super.setAlt(alt);
    }

    @Override
    public PlanificarNotificacion setFields(java.lang.String fields) {
      return (PlanificarNotificacion) super.setFields(fields);
    }

    @Override
    public PlanificarNotificacion setKey(java.lang.String key) {
      return (PlanificarNotificacion) super.setKey(key);
    }

    @Override
    public PlanificarNotificacion setOauthToken(java.lang.String oauthToken) {
      return (PlanificarNotificacion) super.setOauthToken(oauthToken);
    }

    @Override
    public PlanificarNotificacion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (PlanificarNotificacion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public PlanificarNotificacion setQuotaUser(java.lang.String quotaUser) {
      return (PlanificarNotificacion) super.setQuotaUser(quotaUser);
    }

    @Override
    public PlanificarNotificacion setUserIp(java.lang.String userIp) {
      return (PlanificarNotificacion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String pnDiaFin;

    /**

     */
    public java.lang.String getPnDiaFin() {
      return pnDiaFin;
    }

    public PlanificarNotificacion setPnDiaFin(java.lang.String pnDiaFin) {
      this.pnDiaFin = pnDiaFin;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String pnDiaInicio;

    /**

     */
    public java.lang.String getPnDiaInicio() {
      return pnDiaInicio;
    }

    public PlanificarNotificacion setPnDiaInicio(java.lang.String pnDiaInicio) {
      this.pnDiaInicio = pnDiaInicio;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer pnFrecuencia;

    /**

     */
    public java.lang.Integer getPnFrecuencia() {
      return pnFrecuencia;
    }

    public PlanificarNotificacion setPnFrecuencia(java.lang.Integer pnFrecuencia) {
      this.pnFrecuencia = pnFrecuencia;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer pnHoraFin;

    /**

     */
    public java.lang.Integer getPnHoraFin() {
      return pnHoraFin;
    }

    public PlanificarNotificacion setPnHoraFin(java.lang.Integer pnHoraFin) {
      this.pnHoraFin = pnHoraFin;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer pnHoraInicio;

    /**

     */
    public java.lang.Integer getPnHoraInicio() {
      return pnHoraInicio;
    }

    public PlanificarNotificacion setPnHoraInicio(java.lang.Integer pnHoraInicio) {
      this.pnHoraInicio = pnHoraInicio;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String pnTipoFrecuencia;

    /**

     */
    public java.lang.String getPnTipoFrecuencia() {
      return pnTipoFrecuencia;
    }

    public PlanificarNotificacion setPnTipoFrecuencia(java.lang.String pnTipoFrecuencia) {
      this.pnTipoFrecuencia = pnTipoFrecuencia;
      return this;
    }

    @Override
    public PlanificarNotificacion set(String parameterName, Object value) {
      return (PlanificarNotificacion) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link GestionUsuario}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link GestionUsuario}. */
    @Override
    public GestionUsuario build() {
      return new GestionUsuario(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GestionUsuarioRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGestionUsuarioRequestInitializer(
        GestionUsuarioRequestInitializer gestionusuarioRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(gestionusuarioRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
